@startuml
'https://plantuml.com/class-diagram

title ERD Tourismus App
class Route
class Ausgangspunkt
class Endpunkt
class Verlauf
class User

class Sehenswuerdigkeiten {

}

class Kategorie{
    int ID 
    String bezeichnung
    int typeOfPOI
}
class Hotel
class Restaurant {
Speisekarte speisekarte
int hauben 
}
class OeffentlicheVerkehrsmittel
class Standort {
double xKoordinate
double yKoordinate
Adresse adresse
String adresszusatz
}
abstract class PointOfInterest {
int ID
String name
float bewertung
Standort standort 
}

class Adresse{
int lokationsID
int PLZ
String ort 
String strasse 
String hausnr
int stiege
int stock 
int tuer 
}

Kategorie }o--o PointOfInterest

Route *--|| Ausgangspunkt: > hat
Route *--|| Endpunkt: > hat
Route *--|| Verlauf: > hat
User --o{ Route : folgt >
User ||-- Route : ist zugeordnet <

User }o--o| OeffentlicheVerkehrsmittel: > benützt

Adresse ||--o Standort
Endpunkt --|| Standort:  > hat
Ausgangspunkt --|| Standort:  > hat

OeffentlicheVerkehrsmittel --o Route

Standort ||-- PointOfInterest: < hat

Sehenswuerdigkeiten --|> PointOfInterest
Hotel --|> PointOfInterest
Restaurant --|> PointOfInterest
@enduml
